apiVersion: v1
kind: Service
metadata:
  name: pub-site
  namespace: pub-site
  labels:
    app: pub-site
spec:
  type: ClusterIP
  selector:
    app: pub-site
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
