---
apiVersion: v1
kind: Namespace
metadata:
  name: pub-site-dev
  labels:
    name: pub-site-dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pub-site
  namespace: pub-site-dev
  labels:
    app: pub-site
    environment: testing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub-site
      environment: testing
  template:
    metadata:
      labels:
        app: pub-site
        environment: testing
    spec:
      containers:
      - name: pub-site
        image: dremer10/pub-site:test
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "12Mi"
            cpu: "5m"
          limits:
            memory: "24Mi"
            cpu: "25m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: pub-site
  namespace: pub-site-dev
  labels:
    app: pub-site
    environment: testing
spec:
  type: ClusterIP
  selector:
    app: pub-site
    environment: testing
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: pub-site-gateway
  namespace: pub-site-dev
spec:
  gatewayClassName: nginx
  listeners:
  - name: https
    hostname: info-dev.dremer10.com
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: pub-site-testing-tls
        kind: Secret

---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: pub-site
  namespace: pub-site-dev
spec:
  parentRefs:
  - name: pub-site-gateway
  hostnames:
  - info-dev.dremer10.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: pub-site
      port: 80
