apiVersion: v1
kind: Pod
metadata:
  name: prom-lock-fix
  namespace: monitoring-staging
spec:
  restartPolicy: Never
  containers:
  - name: shell
    image: alpine:3.19
    command: ["sh","-c","rm -f /prometheus/lock && sleep 5"]
    volumeMounts:
    - name: data
      mountPath: /prometheus
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: prometheus-pvc
